---
title: "Country Summary"
author: "Gareth"
format: pdf
editor: visual
params:
  country: "Iceland"
---

```{r}
#| echo: false
#| warning: false
library(httr)

responseContent <-
  GET(
    url = sprintf(
      "https://restcountries.com/v3.1/name/%1$s?fullText=true",
      params$country
    ))
    
    if (status_code(responseContent) == 200) {
      details <- content(responseContent)[[1L]]
    } else {
      details <- NULL
    }

```

## Details

`r params$country` is a country in `r details$subregion`. It has a population of  `r details$population`. The capital of city is `r unlist(details$capital)`. The official language(s) are `r paste(unlist(details$languages), collapse = ", ")` with a primary currency of the `r details$currencies[[1L]]$name`. 


## Map

```{r}
#| echo: false
#| warning: false
library(maps)
library(ggplot2)
## make a df with only the country to overlap
countryMap <- map_data('world')[map_data('world')$region == params$country,]

ggplot() +
    ## First layer: worldwide map
    geom_polygon(data = map_data("world"),
                 aes(x=long, y=lat, group = group),
                 color = '#9c9c9c', fill = '#f3f3f3') +
    ## Second layer: Country map
    geom_polygon(data = countryMap,
                 aes(x=long, y=lat, group = group),
                 color = "red", fill = "pink") +
    coord_map() +
    coord_fixed(1.3,
                xlim = c(min(countryMap$long), max(countryMap$long)),
                ylim = c(min(countryMap$lat), max(countryMap$lat))) +
    ggtitle(paste0("Map of", params$country)) +
    theme(panel.background =element_rect(fill = "lightblue"))
```



```{r}
#| echo: false
#| warning: false
library(dplyr)
library(gapminder)

data("gapminder")

filterData <- filter(gapminder, country == params$country)
```

## Life Expectancy 

```{r}
#| echo: false
#| warning: false
plot <- ggplot(gapminder, aes(x = continent, y = lifeExp)) +
  geom_boxplot() +
  geom_jitter(position = position_jitter(width = 0.1, height = 0), alpha = 1 / 4) +
  geom_jitter(data = filterData, position = position_jitter(width = 0.1, height = 0), aes(colour = params$country)) +
  ggtitle(label = "Comparision of Life Expectancy  with other countries",
          subtitle = "Annual Data from Gapminder dataset from 1952 - 2007")
  theme_minimal()
  
  plot
```


```{r}
#| echo: false
#| warning: false
ggplot(filterData, aes(x = year, y = lifeExp)) +
  geom_line() +
  ggtitle(label = "Life Expentancy over time",
          subtitle = "Annual Data from Gapminder dataset from 1952 - 2007")
  theme_minimal()
```
