---
title: "Shiny in Secondary Education"
subtitle: ""
author: "Gareth Burns"
date: 10/10/2024
date-format: long
institute: "Exploristics"
format: 
  revealjs:
    logo: logo.jpg
    slide-number: true
    theme: [default, custom.scss]
    toc: false
    incremental: true
    transition: fade
    background-transition: fade
    auto-stretch: true
    auto-animate: true
execute:
  echo: false
editor: visual
---

## Background

## Contributors


## Objectives

- Fun
- Engaging
- Depth of statistical concepts

## Stroop Test

> Say the background colour of the word, not the word itself[^1]

[^1]: https://en.wikipedia.org/wiki/Stroop_effect accessed on

::: r-hstack
::: {data-id="red" auto-animate-delay="0" style="colour: #2780e3; width: 600px; height: 150px; text-align: center;"}
RED
:::

::: {data-id="red" auto-animate-delay="0" style="color: #000; width: 600px; height: 150px; text-align: center;"}
GREEN
:::

::: {data-id="red" auto-animate-delay="0" style="colour: #2780e3; width: 600px; height: 150px; text-align: center;"}
BLUE
:::
:::

::: r-hstack
::: {data-id="red" auto-animate-delay="0" style="colour: #2780e3; width: 600px; height: 150px; text-align: center;"}
RED
:::

::: {data-id="red" auto-animate-delay="0" style="color: #000; width: 600px; height: 150px; text-align: center;"}
GREEN
:::

::: {data-id="red" auto-animate-delay="0" style="colour: #2780e3; width: 600px; height: 150px; text-align: center;"}
BLUE
:::
:::

::: r-hstack
::: {data-id="red" auto-animate-delay="0" style="colour: #2780e3; width: 600px; height: 150px; text-align: center;"}
RED
:::

::: {data-id="red" auto-animate-delay="0" style="color: #000; width: 600px; height: 150px; text-align: center;"}
GREEN
:::

::: {data-id="red" auto-animate-delay="0" style="colour: #2780e3; width: 600px; height: 150px; text-align: center;"}
BLUE
:::
:::

## Pareto Principle {auto-animate="true" auto-animate-easing="ease-in-out"}

20 percent of the effort to achieve 80% of outcomes.

::: r-hstack
::: {data-id="box1" auto-animate-delay="0" style="background: #2780e3; width: 600px; height: 150px; text-align: center;"}
80%
:::

::: {data-id="box2" auto-animate-delay="0.1" style="background: #3fb618; width: 200px; height: 150px;"}
20%
:::

::: {data-id="box3" auto-animate-delay="0.1" style="width: 200px; height: 150px;"}
:::
:::

## Pareto Principle {auto-animate="true" auto-animate-easing="ease-in-out" visibility="uncounted"}

::: columns
::: {.column width="60%"}
::: r-stack
::: {data-id="box1" style="background: #2780e3; width: 350px; height: 350px; border-radius: 200px;"}
:::

::: {data-id="box2" style="background: #3fb618; width: 100px; height: 100px; border-radius: 200px;"}
:::
:::
:::

::: {.column width="40%"}
::: callout-tip
Ideal for MVP/prototyping!
:::
:::
:::

## Pareto Principle {auto-animate="true" auto-animate-easing="ease-in-out"}

::: columns
::: {.column width="60%"}
Expected time/effort to completion

::: {data-id="box1" auto-animate-delay="0" style="background: #2780e3; width: 200px; height: 150px;"}
:::

Actual time/effort to completion

::: {data-id="box2" auto-animate-delay="0.1" style="background: #3fb618; width: 600px; height: 150px;"}
:::
:::

::: {.column width="40%"}
<div>

::: callout-warning
The expectation from external stakeholders is there's 20% of the effort to completion when there's 80% left. So be sure to manage these expectations!!
:::

</div>
:::
:::

## Agile {auto-animate="true" auto-animate-easing="ease-in-out" visibility="uncounted"}

::: {#agile-principle-2 .callout-note}
## Agile Principle #2

Welcome changing requirements, even late in development. Agile processes harness change for the customer's competitive advantage.
:::

## Agile {auto-animate="true" auto-animate-easing="ease-in-out"}

::: callout-warning
## Agile Principle #2

Welcome changing requirements, even late in development. Agile processes harness change for the customer's competitive advantage.
:::

By failing to prepare for change and you're preparing to fail.

## How I Learned to Stop Worrying and Love the Change Requests

-   Ask questions to understand not to 'gather requirements'
-   Write 'production ready
    -   Modularise code
    -   Test Code

## Aligning UI to Technological & Data Literacy

## What is the Data Literacy of your users?

-   National Curriculum
-   Canvass Expert Opinion
-   Monitor existing users

## Abstract away complexity?

Often we want R to carry out complex statistical functionality on behalf of users and display some business logical to users

> ...if written and mental arithmetic are secure. In both primary and secondary schools, teachers should use their judgement about when ICT tools should be used[^2]

[^2]: https://www.gov.uk/government/publications/national-curriculum-in-england-mathematics-programmes-of-study/national-curriculum-in-england-mathematics-programmes-of-study accessed on 6th August 2024

## 

-   Why include interactivity elements to visualisations?
    -   Reinforce learning
    -   Increase classroom engagement through
    -   Display technological proficiency
    -   Generational shift in expectations from digital natives

## Randomisation into Groups

## Resources

🌐 [PSI Schools Outreach](https://psiweb.org/careers/outreach/schools-outreach)

-   
